"""change session ID to be 32 bytes of base64

Revision ID: 060623cf940f
Revises: f0c99d0db277
Create Date: 2026-07-01 01:17:28.430756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from constants import SESSION_ID_LEN


# revision identifiers, used by Alembic.
revision: str = '060623cf940f'
down_revision: Union[str, None] = 'f0c99d0db277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_session', 'session_id',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=SESSION_ID_LEN),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_session', 'session_id',
               existing_type=sa.String(length=SESSION_ID_LEN),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###
