"""site_user_timestamps_nullable

Revision ID: 0a2c458d1ddd
Revises: a5c42bcdda5c
Create Date: 2025-09-28 20:52:02.486734

"""
from collections.abc import Sequence

from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a2c458d1ddd"
down_revision: str | None = "a5c42bcdda5c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("site_user", "first_logged_in",
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column("site_user", "last_logged_in",
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("site_user", "last_logged_in",
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column("site_user", "first_logged_in",
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
