"""fix max length on computing IDs

Revision ID: 0ae98d0ecf4b
Revises: caa26d56d842
Create Date: 2026-08-15 23:55:15.667626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae98d0ecf4b'
down_revision: Union[str, None] = 'caa26d56d842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_posts', 'computing_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=8),
               existing_nullable=False)
    op.alter_column('election_nominee_application', 'computing_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=8),
               existing_nullable=False)
    op.alter_column('election_nominee_info', 'computing_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=8),
               existing_nullable=False)
    op.alter_column('officer_info', 'computing_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=8),
               existing_nullable=False)
    op.alter_column('officer_term', 'computing_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=8),
               existing_nullable=False)
    op.alter_column('site_user', 'computing_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=8),
               existing_nullable=False)
    op.alter_column('user_session', 'computing_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_session', 'computing_id',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('site_user', 'computing_id',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('officer_term', 'computing_id',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('officer_info', 'computing_id',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('election_nominee_info', 'computing_id',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('election_nominee_application', 'computing_id',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('blog_posts', 'computing_id',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
