"""create honorary member table

Revision ID: 3c00f28c26e2
Revises: 42f855bec532
Create Date: 2026-06-29 15:43:07.361827

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op
from honorary.constants import HONORARY_MEMBER_MAX_LENGTH

# revision identifiers, used by Alembic.
revision: str = "3c00f28c26e2"
down_revision: str | None = "42f855bec532"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "honorary_member",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=HONORARY_MEMBER_MAX_LENGTH), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_honorary_member")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("honorary_member")
    # ### end Alembic commands ###
