"""add site_user_role table

Revision ID: 81f44578da6d
Revises: e63f6e6a5489
Create Date: 2026-08-18 19:45:36.148371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81f44578da6d'
down_revision: Union[str, None] = 'e63f6e6a5489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_user_role',
    sa.Column('computing_id', sa.String(length=16), nullable=False),
    sa.Column('role', sa.Enum('admin', 'exec', 'user', name='role_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('added_by', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['site_user.computing_id'], name=op.f('fk_site_user_role_added_by_site_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['computing_id'], ['site_user.computing_id'], name=op.f('fk_site_user_role_computing_id_site_user')),
    sa.PrimaryKeyConstraint('computing_id', 'role', name=op.f('pk_site_user_role'))
    )
    op.create_index(op.f('ix_site_user_role_role'), 'site_user_role', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_user_role_role'), table_name='site_user_role')
    op.drop_table('site_user_role')
    # ### end Alembic commands ###
