"""update event table to remove frequency and add group id and link table to immage asset table

Revision ID: 943c72510e42
Revises: 81f44578da6d
Create Date: 2026-08-22 12:24:18.921363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '943c72510e42'
down_revision: Union[str, None] = '81f44578da6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_info', sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False))
    op.add_column('event_info', sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False))
    op.add_column('event_info', sa.Column('group_id', sa.Uuid(), nullable=True))
    op.add_column('event_info', sa.Column('location', sa.Text(), nullable=True))
    op.add_column('event_info', sa.Column('organizer', sa.Text(), nullable=True))
    op.add_column('event_info', sa.Column('status', sa.Enum('cancelled', 'scheduled', name='valid_status', native_enum=False, create_constraint=True), nullable=False))
    op.add_column('event_info', sa.Column('image_id', sa.Integer(), nullable=True))
    op.alter_column('event_info', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('event_info', 'name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_event_info_image_id_image_asset'), 'event_info', 'image_asset', ['image_id'], ['image_id'])
    op.drop_column('event_info', 'start_time')
    op.drop_column('event_info', 'repeat_start_date')
    op.drop_column('event_info', 'frequency')
    op.drop_column('event_info', 'end_time')
    op.drop_column('event_info', 'repeat_end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_info', sa.Column('repeat_end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('event_info', sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('event_info', sa.Column('frequency', sa.VARCHAR(length=64), server_default=sa.text("'NONE'::character varying"), autoincrement=False, nullable=False))
    op.add_column('event_info', sa.Column('repeat_start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('event_info', sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_event_info_image_id_image_asset'), 'event_info', type_='foreignkey')
    op.alter_column('event_info', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('event_info', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('event_info', 'image_id')
    op.drop_column('event_info', 'status')
    op.drop_column('event_info', 'organizer')
    op.drop_column('event_info', 'location')
    op.drop_column('event_info', 'group_id')
    op.drop_column('event_info', 'end_datetime')
    op.drop_column('event_info', 'start_datetime')
    # ### end Alembic commands ###
