"""update_officer_term_constraint_71

Revision ID: a5c42bcdda5c
Revises: 876041e5b41c
Create Date: 2025-09-28 18:03:54.856781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c42bcdda5c'
down_revision: Union[str, None] = '876041e5b41c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('election', 'type',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               nullable=False)
    op.create_unique_constraint(op.f('uq_officer_term_computing_id'), 'officer_term', ['computing_id', 'position', 'start_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_officer_term_computing_id'), 'officer_term', type_='unique')
    op.alter_column('election', 'type',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
