"""update_officer_term_constraint_71

Revision ID: a5c42bcdda5c
Revises: 243190df5588
Create Date: 2025-09-28 18:03:54.856781

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5c42bcdda5c"
down_revision: str | None = "243190df5588"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("election", "type",
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               nullable=False)
    op.create_unique_constraint(op.f("uq_officer_term_computing_id"), "officer_term", ["computing_id", "position", "start_date"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_officer_term_computing_id"), "officer_term", type_="unique")
    op.alter_column("election", "type",
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
