"""update event table to have groups, location, organizer and status

Revision ID: b793b71fff3e
Revises: 81f44578da6d
Create Date: 2026-08-28 17:51:07.556757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b793b71fff3e'
down_revision: Union[str, None] = '81f44578da6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_info', sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False))
    op.add_column('event_info', sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False))
    op.add_column('event_info', sa.Column('group_id', sa.Uuid(), nullable=True))
    op.add_column('event_info', sa.Column('location', sa.Text(), nullable=True))
    op.add_column('event_info', sa.Column('organizer', sa.Text(), nullable=True))
    op.add_column('event_info', sa.Column('status', sa.Enum('cancelled', 'scheduled', name='valid_status', native_enum=False, create_constraint=True), nullable=False))
    op.add_column('event_info', sa.Column('url', sa.Text(), nullable=True))
    op.add_column('event_info', sa.Column('image_id', sa.Integer(), nullable=True))
    op.alter_column('event_info', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('event_info', 'name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_event_info_group_id'), 'event_info', ['group_id'], unique=False)
    op.create_foreign_key(op.f('fk_event_info_image_id_image_asset'), 'event_info', 'image_asset', ['image_id'], ['image_id'])
    op.drop_constraint(op.f('ck_event_info_valid_frequency_value'), 'event_info', type_='check')
    op.drop_constraint(op.f('ck_event_info_check_repeat_start_date_before_repeat_end_date'), 'event_info', type_='check')
    op.drop_constraint(op.f('ck_event_info_check_start_time_before_end_time'), 'event_info', type_='check')
    op.create_check_constraint(op.f('ck_event_info_check_start_datetime_before_end_datetime'), 'event_info', 'start_datetime <= end_datetime')
    op.drop_column('event_info', 'end_time')
    op.drop_column('event_info', 'frequency')
    op.drop_column('event_info', 'repeat_end_date')
    op.drop_column('event_info', 'repeat_start_date')
    op.drop_column('event_info', 'start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_info', sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('event_info', sa.Column('repeat_start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('event_info', sa.Column('repeat_end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('event_info', sa.Column('frequency', sa.VARCHAR(length=64), server_default=sa.text("'NONE'::character varying"), autoincrement=False, nullable=False))
    op.add_column('event_info', sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('ck_event_info_check_start_datetime_before_end_datetime'), 'event_info', type_='check')
    op.create_check_constraint(op.f('ck_event_info_check_start_time_before_end_time'), 'event_info', 'start_time < end_time')
    op.create_check_constraint(op.f('ck_event_info_valid_frequency_value'), 'event_info', "frequency IN ('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', 'SEMESTERLY', 'YEARLY')")
    op.create_check_constraint(op.f('ck_event_info_check_repeat_start_date_before_repeat_end_date'), 'event_info', 'repeat_start_date < repeat_end_date')
    op.drop_constraint(op.f('fk_event_info_image_id_image_asset'), 'event_info', type_='foreignkey')
    op.drop_index(op.f('ix_event_info_group_id'), table_name='event_info')
    op.alter_column('event_info', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('event_info', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('event_info', 'image_id')
    op.drop_column('event_info', 'url')
    op.drop_column('event_info', 'status')
    op.drop_column('event_info', 'organizer')
    op.drop_column('event_info', 'location')
    op.drop_column('event_info', 'group_id')
    op.drop_column('event_info', 'end_datetime')
    op.drop_column('event_info', 'start_datetime')
    # ### end Alembic commands ###
