"""Create TransLink static schedule

Revision ID: c1a70c8cfd64
Revises: 0a2c458d1ddd
Create Date: 2026-05-17 16:17:26.176355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1a70c8cfd64'
down_revision: Union[str, None] = '0a2c458d1ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translink_static_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_fetched', sa.Date(), nullable=False),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_translink_static_schedule'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translink_static_schedule')
    # ### end Alembic commands ###
