"""remove site profile pics

Revision ID: caa26d56d842
Revises: 060623cf940f
Create Date: 2026-07-01 02:01:26.412179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa26d56d842'
down_revision: Union[str, None] = '060623cf940f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("site_user", "profile_picture_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("site_user", sa.Column("profile_picture_url", sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
