"""create election tables

Revision ID: cb5df398547c
Revises: 43f71e4bd6fc
Create Date: 2024-08-09 09:36:22.745234

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb5df398547c"
down_revision: str | None = "43f71e4bd6fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("election",
    sa.Column("slug", sa.String(length=32), nullable=False),
    sa.Column("name", sa.String(length=32), nullable=False),
    sa.Column("type", sa.String(length=64), nullable=True),
    sa.Column("date", sa.DateTime(), nullable=True),
    sa.Column("end_date", sa.DateTime(), nullable=True),
    sa.Column("websurvey", sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint("slug")
    )
    op.create_table("election_nominee",
    sa.Column("computing_id", sa.String(length=32), nullable=False),
    sa.Column("full_name", sa.String(length=64), nullable=False),
    sa.Column("facebook", sa.String(length=64), nullable=True),
    sa.Column("instagram", sa.String(length=64), nullable=True),
    sa.Column("email", sa.String(length=64), nullable=True),
    sa.Column("discord", sa.String(length=32), nullable=True),
    sa.Column("discord_id", sa.String(length=18), nullable=True),
    sa.Column("discord_username", sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint("computing_id")
    )
    op.create_table("nominee_speech",
    sa.Column("computing_id", sa.String(length=32), nullable=False),
    sa.Column("nominee_election", sa.String(length=32), nullable=False),
    sa.Column("speech", sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(["computing_id"], ["election_nominee.computing_id"], ),
    sa.ForeignKeyConstraint(["nominee_election"], ["election.slug"], ),
    sa.PrimaryKeyConstraint("computing_id", "nominee_election")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nominee_speech")
    op.drop_table("election_nominee")
    op.drop_table("election")
    # ### end Alembic commands ###
