"""add blog_posts table (modified column name)

Revision ID: ce9a59922b43
Revises: e398258d0c63
Create Date: 2024-08-09 04:25:35.100100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9a59922b43'
down_revision: Union[str, None] = 'e398258d0c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('post_tags', sa.String(length=128), nullable=True))
    op.drop_column('blog_posts', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('tags', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('blog_posts', 'post_tags')
    # ### end Alembic commands ###
