"""create auth redirect table

Revision ID: d170b5f5bf81
Revises: f54416fbc87f
Create Date: 2026-08-18 01:33:12.837319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd170b5f5bf81'
down_revision: Union[str, None] = 'f54416fbc87f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_redirect',
    sa.Column('id', sa.String(length=43), nullable=False),
    sa.Column('return_to', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_redirect'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_redirect')
    # ### end Alembic commands ###
