"""added foreign key to blog table

Revision ID: dc48e5a0bd80
Revises: ce9a59922b43
Create Date: 2024-08-12 17:41:27.832233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc48e5a0bd80'
down_revision: Union[str, None] = 'ce9a59922b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
