"""update user_session table

Revision ID: ddc8f04aea0d
Revises: d170b5f5bf81
Create Date: 2026-08-18 03:47:31.954350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc8f04aea0d'
down_revision: Union[str, None] = 'd170b5f5bf81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'pk_user_session',
        'user_session',
        type_='primary',
    )
    op.drop_constraint(op.f('uq_user_session_session_id'), 'user_session', type_='unique')
    op.create_primary_key('pk_user_session', 'user_session', ['session_id'])
    op.create_index(op.f('ix_user_session_computing_id'), 'user_session', ['computing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_session_computing_id'), table_name='user_session')
    op.drop_constraint('pk_user_session', 'user_session', type_='primary')
    op.create_primary_key('pk_user_session', 'user_session', ['computing_id'])
    op.create_unique_constraint(op.f('uq_user_session_session_id'), 'user_session', ['session_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
