"""add blog_posts table

Revision ID: e398258d0c63
Revises: 43f71e4bd6fc
Create Date: 2024-08-09 02:06:35.816396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e398258d0c63'
down_revision: Union[str, None] = '43f71e4bd6fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_posts',
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('computing_id', sa.String(length=32), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_edited', sa.DateTime(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_posts')
    # ### end Alembic commands ###
