"""user_session: use hash instead of session ID and add expires_at column

Revision ID: e63f6e6a5489
Revises: ddc8f04aea0d
Create Date: 2026-08-18 04:28:51.974508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e63f6e6a5489'
down_revision: Union[str, None] = 'ddc8f04aea0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_session', sa.Column('session_hash', sa.LargeBinary(length=32), nullable=False))
    op.add_column('user_session', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_session', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('user_session', 'session_id')
    op.drop_column('user_session', 'issue_time')
    op.create_primary_key('pk_user_session', 'user_session', ['session_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_session', sa.Column('issue_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('user_session', sa.Column('session_id', sa.VARCHAR(length=43), autoincrement=False, nullable=False))
    op.drop_column('user_session', 'expires_at')
    op.drop_column('user_session', 'created_at')
    op.drop_column('user_session', 'session_hash')
    op.create_primary_key('pk_user_session', 'user_session', ['session_id'])
    # ### end Alembic commands ###
