"""add profile_picture_url to site_user

Revision ID: e74292feb010
Revises: 2a6ea95342dc
Create Date: 2024-10-04 17:23:06.869439

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e74292feb010"
down_revision: str | None = "2a6ea95342dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("site_user", sa.Column("profile_picture_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("site_user", "profile_picture_url")
    # ### end Alembic commands ###
