"""add image_asset table

Revision ID: f54416fbc87f
Revises: 0ae98d0ecf4b
Create Date: 2026-08-16 13:51:25.315806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f54416fbc87f'
down_revision: Union[str, None] = '0ae98d0ecf4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_asset',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('image_id', name=op.f('pk_image_asset')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_image_asset_storage_key'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_asset')
    # ### end Alembic commands ###
